apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: express-microservice
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: express-ci
      eventName: express-ci
      eventSourceName: express-microservice
      filters:
        data:
          - &ref_0
            path: body.X-GitHub-Event
            value:
              - push
            type: string
          - &ref_1
            path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
    - name: express-cd
      eventName: express-cd
      eventSourceName: express-microservice
      filters:
        data:
          - *ref_0
          - *ref_1
          # Filter monorepo changes+additions+deletions for only the "prod" subdirectory
          - path: '{body.commits.#.modified,body.commits.#.added,body.commits.#.removed}'
            type: string
            # Example string: {"modified":[["prod/values.yaml", "prod/chart.yaml"]],"added":[["prod/mynewfile"]],"removed":[["prod/ingress.yaml"]]}
            template: '{{ contains "\"kustomize/express/overlays/dev/" .Input }}'
            value:
              - "true"
  triggers:
    - template:
        name: ci
        conditions: express-ci
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: express-microservice-adv-ci-
              spec:
                arguments:
                  parameters:
                    - name: GIT_REPO_URL
                      value: ''
                    - name: IMAGE_NAME
                      value: ''
                    - name: IMAGE_TAG
                      value: ''
                    - name: GIT_AUTHOR
                      value: ''
                    - name: GIT_REVISION
                      value: ''
                    - name: GIT_BRANCH
                      value: ''
                    - name: GIT_COMMIT_URL
                      value: ''
                    - name: GIT_COMMIT_MESSAGE
                      value: ''
                    - name: DOCKERFILE
                      value: ''
                    - name: GIT_TOKEN_SECRET
                      value: ''
                    - name: CONTEXT
                      value: ''
                    - name: REGISTRY_CREDS_SECRET
                      value: ''
                    - name: DOCKER_CONFIG_SECRET
                      value: ''
                    - name: PROMOTE_TO
                      value: 'dev'
                    - name: APP_PATH_PREFIX
                      value: ''
                    - name: REPO_SLUG
                      value: ''
                workflowTemplateRef:
                  name: ci-and-promote
          parameters:
            - dest: spec.arguments.parameters.0.value
              src:
                dependencyName: express-ci
                dataTemplate: '{{ .Input.body.repository.clone_url }}'
            - dest: spec.arguments.parameters.1.value
              src:
                dependencyName: express-ci
                dataTemplate: quay.io/codefresh_sa/express-microservice
            - dest: spec.arguments.parameters.2.value
              src:
                dependencyName: express-ci
                dataTemplate: '{{ trunc 7 .Input.body.after }}'
            - dest: spec.arguments.parameters.3.value
              src:
                dependencyName: express-ci
                dataTemplate: '{{ .Input.body.sender.login }}'
            - dest: spec.arguments.parameters.4.value
              src:
                dependencyName: express-ci
                dataTemplate: '{{ .Input.body.after }}'
            - dest: spec.arguments.parameters.5.value
              src:
                dependencyName: express-ci
                dataTemplate: '{{ trimPrefix "refs/heads/" .Input.body.ref }}'
            - dest: spec.arguments.parameters.6.value
              src:
                dependencyName: express-ci
                dataTemplate: '{{ .Input.body.head_commit.url }}'
            - dest: spec.arguments.parameters.7.value
              src:
                dependencyName: express-ci
                dataTemplate: '{{ .Input.body.head_commit.message }}'
            - dest: spec.arguments.parameters.8.value
              src:
                dependencyName: express-ci
                dataTemplate: Dockerfile
            - dest: spec.arguments.parameters.9.value
              src:
                dependencyName: express-ci
                dataTemplate: github-token
            - dest: spec.arguments.parameters.10.value
              src:
                dependencyName: express-ci
                dataTemplate: .
            - dest: spec.arguments.parameters.11.value
              src:
                dependencyName: express-ci
                dataTemplate: quay-creds
            - dest: spec.arguments.parameters.12.value
              src:
                dependencyName: express-ci
                dataTemplate: quay-regcreds
            - dest: spec.arguments.parameters.13.value
              src:
                dependencyName: express-ci
                dataTemplate: dev
            - dest: spec.arguments.parameters.14.value
              src:
                dependencyName: express-ci
                dataTemplate: kustomize/express/overlays
            - dest: spec.arguments.parameters.15.value
              src:
                dependencyName: express-ci
                dataTemplate: >-
                  {{ regexReplaceAll "https?://github.com/(.*).git"
                  .Input.body.repository.clone_url "${1}" | trim }}

    - template:
        name: deploy-dev-and-promote
        conditions: express-cd
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: express-microservice-deploy-dev-and-promote-
              spec:
                arguments:
                  parameters:
                    #0
                    - name: ARGOCD_APP
                      value: ''
                    #1
                    - name: ARGOCD_SERVER
                      value: ''
                    #2
                    - name: IMAGE
                      value: ''
                    #3
                    - name: PROMOTE_TO
                      value: ''
                    #4
                    - name: APP_PATH_PREFIX
                      value: ''
                workflowTemplateRef:
                  name: 'kustomize-promote-simple'
          parameters:
            - dest: spec.arguments.parameters.0.value
              src:
                dependencyName: express-cd
                dataTemplate: express-dev
            - dest: spec.arguments.parameters.1.value
              src:
                dependencyName: express-cd
                dataTemplate: argocd-server
            - dest: spec.arguments.parameters.2.value
              src:
                dependencyName: express-cd
                dataTemplate: '{{ splitList " " .Input.body.head_commit.message | last | trim}}'
            - dest: spec.arguments.parameters.3.value
              src:
                dependencyName: express-cd
                dataTemplate: stage
            - dest: spec.arguments.parameters.4.value
              src:
                dependencyName: express-cd
                dataTemplate: kustomize/express/overlays